version: "3.9"
services:
  ###############################################################################
  # Minio Server
  ###############################################################################
  minio:
    image: bitnami/minio:latest
    hostname: minio
    volumes:
     - ${ROGUE_DATA}/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DISTRIBUTED_MODE_ENABLED: "no"
      # MINIO_SERVER_URL: https://minio.roguedev.local
      BITNAMI_DEBUG: 'true'
      TZ: Africa/Gaborone
    networks:
      rogue-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_minio == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rogue-public"

        - traefik.http.routers.minio-https.rule=Host(`${MINIO_DOMAIN}`)
        - traefik.http.routers.minio-https.entrypoints=websecure
        - traefik.http.routers.minio-https.service=minio
        - traefik.http.routers.minio-https.tls=true
        - traefik.http.routers.minio-http.rule=Host(`${MINIO_DOMAIN}`)
        - traefik.http.routers.minio-http.entrypoints=web
        - traefik.http.routers.minio-http.middlewares=https-redirect
        - traefik.http.routers.minio-http.service=minio
        - traefik.http.services.minio.loadbalancer.server.port=9000

        - traefik.http.routers.minio-console-https.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)
        - traefik.http.routers.minio-console-https.entrypoints=websecure
        - traefik.http.routers.minio-console-https.service=minio-console
        - traefik.http.routers.minio-console-https.tls=true
        - traefik.http.routers.minio-console-http.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)
        - traefik.http.routers.minio-console-http.entrypoints=web
        - traefik.http.routers.minio-console-http.middlewares=https-redirect
        - traefik.http.routers.minio-console-http.service=minio-console
        - traefik.http.services.minio-console.loadbalancer.server.port=9001
      
###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    external: true
