version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    # volumes:
      # - ${RIMS_DATA}/oracle-db/oradata:/opt/oracle/oradata
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
      TZ: Africa/Gaborone
    # healthcheck:
    #   test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "--username=postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      rims-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rims_oracle_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rims-public"
        - "traefik.constraint-label=rims-public"
        - "traefik.tcp.routers.rims-oracle-db.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.rims-oracle-db.entrypoints=oracle-db"
        # - "traefik.tcp.routers.rims-oracle-db.service=oracle-db"
        # - "traefik.tcp.routers.rims-db-postgres.tls.certresolver=le"
        - "traefik.tcp.services.rims-oracle-db.loadbalancer.server.port=1521"

###############################################################################
# Networks
###############################################################################
networks:
  rims-public:
    external: true
