version: '3'
volumes:
  prometheus: {}
  prometheus_data: {}
  grafana: {}
  alertmanager: {}
services:
  otel:
    image: 'grafana/otel-lgtm:latest'
    networks:
      rogue-public:
      net:
    volumes:
      - ${ROGUE_DATA}/otel/data:/data
      - ${ROGUE_DATA}/otel/prometheus.yml:/otel-lgtm/prometheus.yaml:ro
      # Extra datasources. A different file name keeps the built-in LGTM datasources.
      # - ${ROGUE_DATA}/otel/config/grafana-datasources.yml:/otel-lgtm/grafana/conf/provisioning/datasources/rogue-datasources.yaml

      # Extra dashboard provider. A different file name keeps the built-in dashboards.
      - ${ROGUE_DATA}/otel/config/grafana-dashboards.yml:/otel-lgtm/grafana/conf/provisioning/dashboards/rogue-dashboards.yaml

      # Dashboard JSON files
      - type: bind
        source: ${ROGUE_DATA}/otel/config/dashboards/grafana-dashboard-container-metrics.json
        target: /otel-lgtm/rogue-dashboards/container-metrics.json
      - type: bind
        source: ${ROGUE_DATA}/otel/config/dashboards/grafana-dashboard-node-metrics.json
        target: /otel-lgtm/rogue-dashboards/node-metrics.json
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PLUGINS_ENABLE_ALPHA=true
      - GF_ALLOW_EMBEDDING=true
      - GF_grafanaconThemes=true
      - ENABLE_LOGS_GRAFANA=true
      - GF_FEATURE_TOGGLES_ENABLE=provisioning,kubernetesDashboards
      - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_SECURITY_ADMIN_USER=${OTEL_ADMIN_USER}
      # - GF_SECURITY_ADMIN_PASSWORD=${OTEL_ADMIN_PASSWORD}
      - TZ=Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rogue-public"
        - "traefik.constraint-label=rogue-public"

        # =========================================================
        # GRAFANA UI - HTTP → HTTPS REDIRECT
        # =========================================================
        - "traefik.http.routers.grafana-ui-http.entrypoints=web"
        - "traefik.http.routers.grafana-ui-http.rule=Host(`${OTEL_DOMAIN}`)"
        - "traefik.http.routers.grafana-ui-http.middlewares=https-redirect"
        - "traefik.http.routers.grafana-ui-http.service=grafana-ui"

        # =========================================================
        # GRAFANA UI - HTTPS
        # =========================================================
        - "traefik.http.routers.grafana-ui.entrypoints=websecure"
        - "traefik.http.routers.grafana-ui.rule=Host(`${OTEL_DOMAIN}`)"
        - "traefik.http.routers.grafana-ui.tls=true"
        - "traefik.http.routers.grafana-ui.tls.certresolver=le"
        - "traefik.http.routers.grafana-ui.service=grafana-ui"

        - "traefik.http.services.grafana-ui.loadbalancer.server.port=3000"

        # ---------------- OTEL (SINGLE ROUTER ONLY) ----------------
        - "traefik.http.routers.otel.entrypoints=websecure"
        - "traefik.http.routers.otel.rule=Host(`${OTEL_METRICS_DOMAIN}`) && (PathPrefix(`/v1/traces`) || PathPrefix(`/v1/metrics`) || PathPrefix(`/v1/logs`))"
        - "traefik.http.routers.otel.tls=true"
        - "traefik.http.routers.otel.tls.certresolver=le"
        - "traefik.http.routers.otel.service=otel"

        - "traefik.http.services.otel.loadbalancer.server.port=4318"

        # =========================================================
        # PROMETHEUS - HTTP → HTTPS REDIRECT
        # =========================================================
        - "traefik.http.routers.otel-prom-http.entrypoints=web"
        - "traefik.http.routers.otel-prom-http.rule=Host(`${OTEL_PROM_DOMAIN}`)"
        - "traefik.http.routers.otel-prom-http.middlewares=https-redirect"
        - "traefik.http.routers.otel-prom-http.service=otel-prom"

        # =========================================================
        # PROMETHEUS - HTTPS
        # =========================================================
        - "traefik.http.routers.otel-prom.entrypoints=websecure"
        - "traefik.http.routers.otel-prom.rule=Host(`${OTEL_PROM_DOMAIN}`)"
        - "traefik.http.routers.otel-prom.tls=true"
        - "traefik.http.routers.otel-prom.tls.certresolver=le"
        - "traefik.http.routers.otel-prom.service=otel-prom"

        - "traefik.http.services.otel-prom.loadbalancer.server.port=9090"

  
  dockerd-exporter:
    image: stefanprodan/caddy
    networks:
      - net
    environment:
      - DOCKER_GWBRIDGE_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    command:
      - '-logtostderr'
      - '-docker_only'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /dev/disk
        target: /dev/disk
        read_only: true                        
    networks:
      - net

  
  alertmanager:
    image: stefanprodan/swarmprom-alertmanager:v0.15.3
    networks:
      - default
      - net
      - rogue-public
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
        # - ${ROGUE_DATA}/auth/system_passwd:/var/system_passwd
      # - ./swarmprom_passwd:/swarmprom_passwd
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=rogue-public
        - traefik.constraint-label=rogue-public
        - traefik.http.routers.swarmprom-alertmanager-http.rule=Host(`alertmanager.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-alertmanager-http.entrypoints=${WEB_ENTRY}
        - traefik.http.routers.swarmprom-alertmanager-http.middlewares=https-redirect
        - traefik.http.routers.swarmprom-alertmanager-https.rule=Host(`alertmanager.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-alertmanager-https.entrypoints=${WEBSECURE_ENTRY}
        - traefik.http.routers.swarmprom-alertmanager-https.tls=${SSL_SECURE}
        - traefik.http.routers.swarmprom-alertmanager-https.tls.certresolver=le
        - traefik.http.services.swarmprom-alertmanager.loadbalancer.server.port=9093
        # - traefik.http.middlewares.swarmprom-alertmanager-auth.basicauth.usersfile=/var/system_passwd
        # - traefik.http.routers.swarmprom-alertmanager-https.middlewares=swarmprom-alertmanager-auth

  unsee:
    image: cloudflare/unsee:v0.9.2
    networks:
      - default
      - net
      - rogue-public
    # volumes:
      # - ${ROGUE_DATA}/auth/system_passwd:/var/system_passwd
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=rogue-public
        - traefik.constraint-label=rogue-public
        - traefik.http.routers.swarmprom-unsee-http.rule=Host(`unsee.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-unsee-http.entrypoints=${WEB_ENTRY}
        - traefik.http.routers.swarmprom-unsee-http.middlewares=https-redirect
        - traefik.http.routers.swarmprom-unsee-https.rule=Host(`unsee.${DOMAIN?Variable not set}`)
        - traefik.http.routers.swarmprom-unsee-https.entrypoints=${WEBSECURE_ENTRY}
        - traefik.http.routers.swarmprom-unsee-https.tls=${SSL_SECURE}
        - traefik.http.routers.swarmprom-unsee-https.tls.certresolver=le
        - traefik.http.services.swarmprom-unsee.loadbalancer.server.port=8080
        # - traefik.http.middlewares.swarmprom-unsee-auth.basicauth.usersfile=/var/system_passwd
        # - traefik.http.routers.swarmprom-unsee-https.middlewares=swarmprom-unsee-auth

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
    networks:
      - net

configs:
  dockerd_config:
    file: ${ROGUE_DATA}/caddy/Caddyfile
  # node_rules:
    # file: ${ROGUE_DATA}/prometheus/rules/swarm_node.rules.yml
  # task_rules:
    # file: ${ROGUE_DATA}/prometheus/rules/swarm_task.rules.yml

###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    external: true
  net:
    driver: overlay
    attachable: true