version: '3.8'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '5432:5432'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    networks:
      - rogue-public
    volumes:
      - ${ROGUE_DATA}/letsencrypt:/etc/letsencrypt
      # - ./proxy.roguedev.local.conf:/data/nginx/proxy_host/proxy.roguedev.local.conf
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_proxy == true
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d your-domain.com
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
configs:
  nginx-config:
    file: ./deployment/nginx/nginx.conf
      
networks:
  # Use the previously created public network "rogue-public", shared with other
  # services that need to be publicly available via this Traefik
  rogue-public:
    external: true