version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  postgres-db:
    hostname: db
    image: bitnami/postgresql:16
    volumes:
      - ${RIMS_DATA}/postgres:/bitnami/postgresql
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      TZ: Africa/Gaborone
    # depends_on:
    #   proxy:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "--username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      rims-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rims_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rims-public"
        - "traefik.constraint-label=rims-public"
        - "traefik.tcp.routers.rims-db-postgres.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.rims-db-postgres.entrypoints=postgres"
        - "traefik.tcp.routers.rims-db.service=postgres"
        # - "traefik.tcp.routers.rims-db-postgres.tls.certresolver=le"
        - "traefik.tcp.services.rims-db.loadbalancer.server.port=5432"

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
      # - DATA_SOURCE_USER=bocraportal
      # - DATA_SOURCE_PASS=Cash8Aes
    ports:
      - 9187:9187
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rims_db == true
    networks:
      rims-public:

###############################################################################
# Networks
###############################################################################
networks:
  rims-public:
    external: true
