version: "3.9"
services:
  ###############################################################################
  # MS SQL 2019 Server
  ###############################################################################
  mssql:
    image: mcr.microsoft.com/mssql/rhel/server:2019-latest
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RxH4uloM!
      - TZ=Africa/Gaborone
    networks:
      rims-public:
      default:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rims_mssql == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rims-public"
        - "traefik.constraint-label=rims-public"
        - "traefik.tcp.routers.rims-mssql.rule=HostSNI(`mssql.rimsdev.local`)"
        - "traefik.tcp.routers.rims-mssql.entrypoints=mssql"
        - "traefik.tcp.routers.rims-mssql.service=rims-mssql"
        - "traefik.tcp.routers.rims-mssql.tls=true"
        - "traefik.tcp.routers.rims-mssql.tls.passthrough=true"
        - "traefik.tcp.services.rims-mssql.loadbalancer.server.port=1433"

###############################################################################
# Networks
###############################################################################
networks:
  rims-public:
    external: true
