version: "3.9"
services:
  ###############################################################################
  # Postgres database
  ###############################################################################
  postgres-db:
    hostname: db
    image: bitnami/postgresql:15
    volumes:
      - ${ROGUE_DATA}/postgres:/bitnami/postgresql
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      TZ: Africa/Gaborone
    # depends_on:
    #   proxy:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/bitnami/postgresql/bin/pg_isready", "--username=postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      rogue-public:
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rogue-public"
        - "traefik.constraint-label=rogue-public"
        - "traefik.tcp.routers.rogue-db-postgres.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.rogue-db-postgres.entrypoints=postgres"
        - "traefik.tcp.routers.rogue-db.service=postgres"
        # - "traefik.tcp.routers.rogue-db-postgres.tls.certresolver=le"
        - "traefik.tcp.services.rogue-db.loadbalancer.server.port=5432"

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
      # - DATA_SOURCE_USER=bocraportal
      # - DATA_SOURCE_PASS=Cash8Aes
    ports:
      - 9187:9187
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true
    networks:
      rogue-public:

  ###############################################################################
  # Postgres administration frontend
  ###############################################################################
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:7
    networks:
      rogue-public:
    # depends_on:
      # proxy:
      #   condition: service_healthy
      # db:
      #  condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
      TZ: Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_proxy == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rogue-public"
        - "traefik.constraint-label=rogue-public"
        - "traefik.http.routers.rogue-pgadmin-http.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.rogue-pgadmin-http.entrypoints=web"
        - "traefik.http.routers.rogue-pgadmin-http.middlewares=https-redirect"
        - "traefik.http.services.rogue-pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.rogue-pgadmin-https.entrypoints=websecure"
        - "traefik.http.routers.rogue-pgadmin-https.rule=Host(`${DB_DOMAIN}`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.routers.rogue-pgadmin-https.tls=true"
        - "traefik.http.routers.rogue-pgadmin-https.tls.certresolver=le"

###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    external: true
