version: '3'

services:
  mysql-primary:
    image: bitnami/mysql:8.4.5
    environment:
      - BITNAMI_DEBUG=true
      - MYSQL_SKIP_INITIALIZATION_ON_RESTART=true  
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=replicate
      - MYSQL_REPLICATION_PASSWORD=replicate
      - MYSQL_ROOT_PASSWORD=openmrs
      - MYSQL_USER=openmrs
      - MYSQL_PASSWORD=openmrs
      - MYSQL_DATABASE=openmrs
    volumes:
      - /home/junior/docker/rogue/mysql/primaryx:/bitnami/mysql
      - /home/junior/docker/rogue/mysql/init2:/docker-entrypoint-initdb.d
    ports:
      - "3306"
    networks:
      - rogue-public
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true

  mysql-replica:
    image: bitnami/mysql:8.4.5
    environment:
      - BITNAMI_DEBUG=true
      - MYSQL_SKIP_INITIALIZATION_ON_RESTART=true  
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_USER=openmrs
      - MYSQL_PASSWORD=openmrs
      - MYSQL_REPLICATION_USER=replicate
      - MYSQL_REPLICATION_PASSWORD=replicate
      - MYSQL_MASTER_HOST=mysql-primary
      - MYSQL_MASTER_ROOT_PASSWORD=openmrs
    volumes:
      - /home/junior/docker/rogue/mysql/replicax:/bitnami/mysql
    ports:
      - "3306"
    networks:
      - rogue-public
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true

###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    external: true
