version: '3'

services:
  otel:
    image: 'grafana/otel-lgtm:latest'
    networks:
      rogue-public:
    volumes:
      - ${ROGUE_DATA}/otel/data:/data
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PLUGINS_ENABLE_ALPHA=true
      - GF_ALLOW_EMBEDDING=true
      - GF_grafanaconThemes=true
      - ENABLE_LOGS_GRAFANA=true
      - GF_FEATURE_TOGGLES_ENABLE=provisioning,kubernetesDashboards
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - TZ=Africa/Gaborone
    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.rogue_db == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rogue-public"
        - "traefik.constraint-label=rogue-public"

        # =========================================================
        # GRAFANA UI - HTTP → HTTPS REDIRECT
        # =========================================================
        - "traefik.http.routers.grafana-ui-http.entrypoints=web"
        - "traefik.http.routers.grafana-ui-http.rule=Host(`${OTEL_DOMAIN}`)"
        - "traefik.http.routers.grafana-ui-http.middlewares=https-redirect"
        - "traefik.http.routers.grafana-ui-http.service=grafana-ui"

        # =========================================================
        # GRAFANA UI - HTTPS
        # =========================================================
        - "traefik.http.routers.grafana-ui.entrypoints=websecure"
        - "traefik.http.routers.grafana-ui.rule=Host(`${OTEL_DOMAIN}`)"
        - "traefik.http.routers.grafana-ui.tls=true"
        - "traefik.http.routers.grafana-ui.tls.certresolver=le"
        - "traefik.http.routers.grafana-ui.service=grafana-ui"

        - "traefik.http.services.grafana-ui.loadbalancer.server.port=3000"

        # ---------------- OTEL (SINGLE ROUTER ONLY) ----------------
        - "traefik.http.routers.otel.entrypoints=websecure"
        - "traefik.http.routers.otel.rule=Host(`${OTEL_METRICS_DOMAIN}`) && (PathPrefix(`/v1/traces`) || PathPrefix(`/v1/metrics`) || PathPrefix(`/v1/logs`))"
        - "traefik.http.routers.otel.tls=true"
        - "traefik.http.routers.otel.tls.certresolver=le"
        - "traefik.http.routers.otel.service=otel"

        - "traefik.http.services.otel.loadbalancer.server.port=4318"
  
###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    external: true