version: "3.9"
services:
  ###############################################################################
  # Traefik proxy
  ###############################################################################
  proxy:
    image: traefik:2.8
    container_name: rogue-proxy
    hostname: traefik
    restart: unless-stopped
    networks:
      rogue-network:
      rogue-public:
      default:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROGUE_DATA}/traefik/acme.json:${ROGUE_DATA}/traefik/acme.json
      - ./traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    ports:
      - "443:443"
      - "80:80"
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:8082/ping","--spider" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.ping.address=:8082"
      - "--log.level=DEBUG"
      - "--accessLog"
      - "--accesslog=true"
      - "--api"
      - "--api.dashboard"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--metrics"
      - "--metrics.prometheus"
      - "--providers.docker.network=rogue-public"
      - "--providers.docker"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.email=${ACME_EMAIL?Variable not set}"
      - "--certificatesresolvers.le.acme.storage=${ROGUE_DATA}/traefik/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`${PROXY_DOMAIN}`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=le"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.rogue.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

  ###############################################################################
  # Local docker container registry
  ###############################################################################
  registry:
    image: registry:2
    container_name: rogue-registry
    ports:
      - 5000:5000
    depends_on:
      - keycloak
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      # REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/localhost_trust_chain.pem
      # REGISTRY_AUTH_TOKEN_REALM: ${KEYCLOAK_AUTH_URL}/realms/${KEYCLOAK_REALM}/protocol/docker-v2/auth
      # REGISTRY_AUTH_TOKEN_SERVICE: ${REGISTRY_CLIENT}
      # REGISTRY_AUTH_TOKEN_ISSUER: ${KEYCLOAK_AUTH_URL}/realms/${KEYCLOAK_REALM}
      # REGISTRY_HTTP_TLS_CERTIFICATE: ${REGISTRY_HTTP_TLS_CERTIFICATE}
      # REGISTRY_HTTP_TLS_KEY: ${REGISTRY_HTTP_TLS_KEY}

      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/localhost.crt
      REGISTRY_HTTP_TLS_KEY: /certs/localhost.key
      REGISTRY_AUTH_TOKEN_REALM: https://app.local/auth/realms/rogue-it/protocol/docker-v2/auth
      REGISTRY_AUTH_TOKEN_SERVICE: rogue-registry
      REGISTRY_AUTH_TOKEN_ISSUER: https://app.local/auth/realms/rogue-it
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/localhost_trust_chain.pem
    volumes:
      - /rogue/registry/data:/var/lib/registry
      - /home/junior/programming/docker/keycloak-docker-compose-yaml/certs:/certs
    networks:
      rogue-network:
      rogue-public:
      default:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rogue-registry.entrypoints=websecure"
      # - "traefik.http.routers.rogue-registry.rule=Host(`${REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.rogue-registry.rule=Host(`registry.monitor.local`)"
      - "traefik.http.routers.rogue-registry.tls=true"


###############################################################################
# Networks
###############################################################################
networks:
  rogue-public:
    # Allow setting it to false for testing
    external: true
  rogue-network:
    name: rogue-network
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.57.0/24
  rogue-elk:
    name: rogue-elk
    driver: bridge
